In [1]:
import pickle
import pandas as pd

In [2]:
# Read the preprocessed CSV file
dataset = pd.read_csv('preprocessed.csv')
dataset

,min_sip,min_lumpsum,expense_ratio,fund_size_cr,fund_age_yr,risk_level,rating,returns_1yr,returns_3yr,returns_5yr,sortino,alpha,sd,beta,sharpe
0,100,100,0.27,10,10,3,3,4.0,6.5,6.9,0.32,2.24,9.39,0.01,0.24
1,1000,1000,0.36,4288,10,1,3,5.6,4.8,5.5,1.33,1.53,0.72,0.56,1.1
2,1000,1000,0.53,157,10,5,3,2.0,18.9,9.7,3.44,2.67,10.58,0.67,1.42
3,500,1000,0.76,637,4,6,2,-0.7,17.1,0.0,2.18,-6.37,14.99,0.85,0.9
4,100,100,0.61,6386,10,6,4,4.5,18.6,9.7,3.69,1.99,10.38,0.68,1.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,500,500,0.35,1238,5,1,3,5.6,4.6,5.4,1.08,1.45,0.72,0.64,0.82
145,500,500,0.33,2463,10,2,3,4.0,6.4,6.9,1.59,4.78,1.87,2.4,0.84
146,500,500,0.39,333,10,3,3,3.8,6.1,4.9,0.98,1.17,2.36,1.02,0.62
147,500,500,0.25,2065,5,3,2,2.6,5.6,0.0,0.59,0.76,2.16,0.73,0.45
148,500,500,0.38,210,10,4,3,10.8,6.6,4.5,1.23,2.84,4.32,0.26,0.58

In [3]:
loaded_model=pickle.load(open("Finalized_model.sav",'rb'))

In [5]:
min_sip = int(input("Enter min_sip: "))
min_lumpsum = int(input("Enter min_lumpsum: "))
fund_size_cr = int(input("Enter fund_size_cr: "))
fund_age_yr = int(input("Enter fund_age_yr: "))
risk_level = int(input("Enter risk_level: "))
rating = int(input("Enter rating: "))
returns_1yr = float(input("Enter returns_1yr: "))
returns_3yr = float(input("Enter returns_3yr: "))
returns_5yr = float(input("Enter returns_5yr: "))

Enter min_sip:  100
Enter min_lumpsum:  100
Enter fund_size_cr:  23
Enter fund_age_yr:  10
Enter risk_level:  3
Enter rating:  3
Enter returns_1yr:  4
Enter returns_3yr:  6
Enter returns_5yr:  6

In [6]:
returns=loaded_model.predict([[min_sip,min_lumpsum,fund_size_cr,fund_age_yr,risk_level,rating,returns_1yr,returns_3yr,returns_5yr]])
returns

array([0.76589906], dtype=float32)